# Generated by Django 4.1.5 on 2023-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_passw_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passw',
            name='passw',
            field=models.BinaryField(),
        ),
    ]
