# Generated by Django 4.1.5 on 2023-01-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_passw_passw'),
    ]

    operations = [
        migrations.AddField(
            model_name='passw',
            name='nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passw',
            name='tag',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
